"""
app/models/schemas.py
---------------------
All Pydantic request and response models for the FastAPI application.

These are the shapes of JSON that cross the HTTP boundary — nothing else
in the codebase should define request/response types.

Models
------
ChatRequest     POST /api/chat   — body sent by the React frontend
ChatResponse    POST /api/chat   — body returned to the React frontend
SourceDoc       (nested)         — one cited source inside ChatResponse
UploadResponse  POST /api/upload — confirmation returned after PDF upload
DocumentInfo    GET  /api/documents — one entry in the document list
HealthResponse  GET  /api/health — server status
"""

from typing import List, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# /ask  — simple request / response  (exact shape requested by the client)
# ---------------------------------------------------------------------------

class AskRequest(BaseModel):
    """Body for POST /ask — a single question string, nothing else."""
    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="A college admission question.",
        examples=["What is the eligibility for B.Tech CSE?"],
    )


class AskSource(BaseModel):
    """One source citation in the /ask response."""
    document: str = Field(
        ...,
        description="Name of the PDF document the answer was found in.",
        examples=["admission_brochure_2024.pdf"],
    )
    page: int = Field(
        ...,
        ge=1,
        description="Page number inside the document (1-based).",
        examples=[12],
    )


class AskResponse(BaseModel):
    """Body returned by POST /ask."""
    answer: str = Field(
        ...,
        description="Answer generated by IBM Granite from the retrieved documents.",
    )
    sources: List[AskSource] = Field(
        default_factory=list,
        description="Documents and pages the answer was drawn from.",
    )


# ---------------------------------------------------------------------------
# /api/chat  — request
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    """
    Body sent by the frontend for each chat turn.

    Fields
    ------
    question   : the user's raw question string (required, non-empty)
    session_id : optional opaque identifier for the browser session.
                 Not used for stateful memory yet; reserved for future use.
    """
    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's question about college admissions.",
        examples=["What are the eligibility criteria for B.Tech?"],
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session identifier (reserved for future use).",
    )


# ---------------------------------------------------------------------------
# /api/chat  — response (nested types first)
# ---------------------------------------------------------------------------

class SourceDoc(BaseModel):
    """
    One source citation attached to a chat answer.

    Every field that was stored in ChromaDB chunk metadata is surfaced here
    so the frontend can display rich citations.
    """
    file_name: str = Field(
        ...,
        description="Name of the PDF file the chunk was extracted from.",
        examples=["admission_brochure_2024.pdf"],
    )
    page: int = Field(
        ...,
        ge=1,
        description="1-based page number within the PDF.",
        examples=[4],
    )
    admission_year: str = Field(
        default="",
        description=(
            "Admission year found in the document, e.g. '2024'. "
            "Empty string when the document does not mention a year."
        ),
        examples=["2024"],
    )


class ChatResponse(BaseModel):
    """
    Body returned by POST /api/chat.

    Fields
    ------
    answer         : Granite's answer text, or the 'not found' message.
    sources        : list of deduplicated source citations (may be empty when
                     the answer is the 'not found' message).
    retrieval_count: number of document chunks that were retrieved from
                     ChromaDB before being passed to Granite.  Useful for
                     debugging and for the frontend's "sources" panel.
    """
    answer: str = Field(
        ...,
        description="The answer generated by IBM Granite.",
    )
    sources: List[SourceDoc] = Field(
        default_factory=list,
        description="Source documents cited in the answer.",
    )
    retrieval_count: int = Field(
        default=0,
        description="Number of chunks retrieved from ChromaDB for this question.",
    )


# ---------------------------------------------------------------------------
# /api/eligibility  — request and response
# ---------------------------------------------------------------------------

class EligibilityRequest(BaseModel):
    """
    Body sent by the eligibility checker form.

    All marks are percentages (0–100). preferred_course is the course name
    the student is interested in, e.g. "B.Tech CSE" or "MBA".
    """
    percentage_12th: float = Field(
        ...,
        ge=0,
        le=100,
        description="Overall 12th grade percentage (0–100).",
        examples=[85.5],
    )
    maths_marks: float = Field(
        ...,
        ge=0,
        le=100,
        description="Mathematics marks in 12th grade (0–100).",
        examples=[90.0],
    )
    physics_marks: float = Field(
        ...,
        ge=0,
        le=100,
        description="Physics marks in 12th grade (0–100).",
        examples=[88.0],
    )
    chemistry_marks: float = Field(
        ...,
        ge=0,
        le=100,
        description="Chemistry marks in 12th grade (0–100).",
        examples=[82.0],
    )
    preferred_course: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="The course the student wants to check eligibility for.",
        examples=["B.Tech CSE"],
    )


class EligibilitySource(BaseModel):
    """One source citation inside EligibilityResponse."""
    document: str = Field(..., description="PDF file name.")
    page: int     = Field(..., ge=1, description="1-based page number.")


class EligibilityResponse(BaseModel):
    """
    Body returned by POST /api/eligibility.

    Fields
    ------
    analysis   : Granite's full eligibility analysis text.
    disclaimer : Fixed disclaimer — eligibility does not guarantee admission.
    sources    : Document citations used in the analysis.
    """
    analysis:   str = Field(..., description="Eligibility analysis from IBM Granite.")
    disclaimer: str = Field(..., description="Mandatory admission disclaimer.")
    sources: List[EligibilitySource] = Field(
        default_factory=list,
        description="Source documents cited in the analysis.",
    )


# ---------------------------------------------------------------------------
# /api/upload  — response
# ---------------------------------------------------------------------------

class UploadResponse(BaseModel):
    """
    Returned after a PDF is uploaded and successfully ingested.
    """
    message: str = Field(
        ...,
        description="Human-readable status message.",
        examples=["Successfully ingested admission_brochure_2024.pdf"],
    )
    file_name: str = Field(
        ...,
        description="Name of the uploaded file.",
        examples=["admission_brochure_2024.pdf"],
    )
    chunks: int = Field(
        ...,
        description="Number of text chunks stored in ChromaDB.",
        examples=[87],
    )


# ---------------------------------------------------------------------------
# /api/documents  — list entry
# ---------------------------------------------------------------------------

class DocumentInfo(BaseModel):
    """
    Metadata about one ingested PDF document.
    Returned as a list by GET /api/documents.
    """
    file_name: str = Field(..., description="PDF file name.")
    file_size_kb: float = Field(..., description="File size in kilobytes.")


# ---------------------------------------------------------------------------
# /api/health  — response
# ---------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """
    Returned by GET /api/health.
    """
    status: str = Field(
        default="ok",
        description="'ok' when the server is running normally.",
    )
    vectorstore_ready: bool = Field(
        ...,
        description=(
            "True when the ChromaDB collection exists and contains at least "
            "one document chunk.  False means ingest.py has not been run yet."
        ),
    )
    collection_name: str = Field(
        ...,
        description="Name of the active ChromaDB collection.",
    )
    document_count: int = Field(
        default=0,
        description="Total number of chunks stored in ChromaDB.",
    )
